export const portfolioData = {
  header: {
    logo: "AA",
    navLinks: [
      { name: "About", href: "#about" },
      { name: "Skills", href: "#skills" },
      { name: "Experience", href: "#experience" },
      { name: "Projects", href: "#projects" },
      { name: "Blog", href: "#publications" },
      { name: "Community", href: "#community" },
      { name: "Education", href: "#education" },
      { name: "Contact", href: "#contact" },
    ],
  },
  hero: {
    eyebrow: "Open to new opportunities · Jaipur, Rajasthan",
    firstName: "Ashutosh",
    lastName: "Ahirwal",
    role: "Senior Drupal Frontend Developer",
    subtitle: "5+ years crafting enterprise digital experiences",
    ctaPrimary: { text: "View Work", href: "#projects" },
    ctaSecondary: { text: "Get In Touch", href: "#contact" },
    badges: [
      "105+ Drupal.org Credits",
      "Drupal 8 / 9 / 10 / 11",
      "SDC · Storybook · Pattern Lab",
      "Published Technical Author",
      "15+ Enterprise Projects",
    ],
  },
  statsBand: [
    { num: "5+", label: "Years Experience" },
    { num: "105+", label: "Drupal.org Credits" },
    { num: "15+", label: "Enterprise Projects" },
    { num: "3", label: "Companies" },
  ],
  about: {
    label: "About Me",
    heading: "Building the web, \none module at a time.",
    description: [
      "I'm a **Senior Drupal Frontend Developer** with 5+ years building scalable, accessible, high-performance digital solutions on **Drupal 8, 9, 10, and 11**.",
      "Deep expertise in **Twig, SDC, Layout Builder**, and modern workflows using **Storybook, Pattern Lab, and Tailwind CSS**. Currently crafting enterprise platforms at **Dotsquares India** in Jaipur.",
      "Active Drupal community contributor with **105+ credits**, module maintainer on Drupal.org, and published technical author on the Specbee blog.",
    ],
    stats: [
      { num: "5+", label: "Years in Drupal" },
      { num: "105+", label: "Community Credits" },
      { num: "15+", label: "Enterprise Projects" },
      { num: "D11", label: "Latest Drupal" },
    ],
  },
  skills: {
    label: "Expertise",
    heading: "What I work with",
    categories: [
      {
        title: "Drupal CMS",
        icon: "⬡",
        tags: [
          { name: "Drupal 8/9/10/11", gold: true },
          { name: "Custom Theming", gold: true },
          { name: "SDC", gold: true },
          { name: "Layout Builder" },
          { name: "Custom Modules" },
          { name: "Views" },
          { name: "Paragraphs" },
          { name: "Webform" },
          { name: "Taxonomy" },
          { name: "Media" },
          { name: "Migrations" },
        ],
      },
      {
        title: "Frontend",
        icon: "⬡",
        tags: [
          { name: "Twig", gold: true },
          { name: "Tailwind CSS", gold: true },
          { name: "HTML5 / CSS3", gold: true },
          { name: "JavaScript ES6+", gold: true },
          { name: "jQuery" },
          { name: "SASS / SCSS / LESS" },
          { name: "Flexbox / Grid" },
          { name: "Bootstrap" },
          { name: "WCAG A11y" },
          { name: "SEO" },
        ],
      },
      {
        title: "Component Tools",
        icon: "⬡",
        tags: [
          { name: "Storybook", gold: true },
          { name: "Pattern Lab", gold: true },
          { name: "SDC Integration" },
          { name: "Design Systems" },
          { name: "Drush" },
          { name: "Composer" },
          { name: "Config Mgmt" },
          { name: "Elastic Search" },
        ],
      },
      {
        title: "DevOps & Tools",
        icon: "⬡",
        tags: [
          { name: "Git / GitHub", gold: true },
          { name: "Bitbucket" },
          { name: "Pantheon" },
          { name: "Docker / DDEV" },
          { name: "Jira" },
          { name: "Monday.com" },
          { name: "ClickUp" },
          { name: "VS Code" },
        ],
      },
      {
        title: "Backend & API",
        icon: "⬡",
        tags: [
          { name: "PHP", gold: true },
          { name: "MySQL" },
          { name: "REST API" },
          { name: "JSON API" },
          { name: "Responsive Images" },
          { name: "AI Code Review" },
        ],
      },
      {
        title: "Soft Skills",
        icon: "⬡",
        tags: [
          { name: "Team Mentoring", gold: true },
          { name: "Client Communication" },
          { name: "Code Review" },
          { name: "Pair Programming" },
          { name: "Documentation" },
          { name: "Cross-functional" },
        ],
      },
    ],
  },
  experience: {
    label: "Experience",
    heading: "Career Journey",
    items: [
      {
        date: "Sep 2025 — Present · Current",
        role: "Programmer Analyst — Frontend Drupal",
        company: "Dotsquares India",
        location: "Jaipur, Rajasthan",
        description: [
          "Leading frontend development and site-building for multiple Drupal 9/10 enterprise projects from inception to delivery.",
          "Architecting reusable component libraries using SDC (Single Directory Components) integrated with Layout Builder and Pattern Lab.",
          "Building custom Drupal themes from scratch with Storybook-driven workflows for design consistency and developer handoff.",
          "Collaborating with backend teams to define content architecture using Paragraphs, Views, and Taxonomy.",
        ],
        tags: ["Drupal 9/10", "SDC", "Storybook", "Pattern Lab", "Layout Builder"],
        current: true,
      },
      {
        date: "Sep 2022 — Sep 2025 · 3 Years",
        role: "Senior Drupal Frontend Developer",
        company: "Specbee Consulting Pvt Ltd",
        location: "Bangalore, Karnataka",
        description: [
          "Delivered custom Drupal 9/10 themes for enterprise clients including **Apollo Hospitals, Nerivio, and Heritage Foundation**.",
          "Led component-based frontend development using SDC, Pattern Lab, and Storybook — reducing design inconsistencies and accelerating UI delivery.",
          "Implemented Tailwind CSS-based theming for Nerivio, replacing legacy CSS with utility-first architecture that cut stylesheet size significantly.",
          "Built and maintained Layout Builder solutions enabling non-technical editors to manage complex page layouts independently.",
          "Authored 3+ technical blog posts on Drupal theming and SDC architecture on the Specbee Blog.",
          "Mentored 2–3 junior frontend developers through code reviews, pair programming, and documentation.",
          "Submitted patches to Drupal core during community contribution sprints.",
        ],
        tags: [
          "Drupal 9/10",
          "SDC",
          "Tailwind CSS",
          "Storybook",
          "Apollo Hospitals",
          "Mentoring",
        ],
      },
      {
        date: "Jan 2021 — Sep 2022 · 1.5 Years",
        role: "Drupal Developer",
        company: "Smashing Infolabs Pvt Ltd",
        location: "Indore, Madhya Pradesh",
        description: [
          "Developed custom Drupal 8 themes and frontend components for clients including **EDB (EnterpriseDB), Barbeque Nation, and Great Southern Homes**.",
          "Built Drupal modules and configured Webform, Views, and Paragraphs for structured content management.",
          "Implemented Elastic Search integration for Great Southern Homes, improving search performance across large content libraries.",
          "Delivered full custom redesigns for clients such as Ubicquia, maintaining brand consistency with pixel-perfect theming.",
        ],
        tags: ["Drupal 8", "Custom Theming", "Elastic Search", "Webform", "Module Dev"],
      },
    ],
  },
  projects: {
    label: "Projects",
    heading: "Notable Work",
    intro: "15+ enterprise projects across healthcare, finance, education, and F&B — spanning Drupal 8, 9 & 10.",
    featured: [
      {
        num: "01",
        category: "Healthcare · Drupal 9",
        title: "Apollo Hospitals",
        description: "Enterprise healthcare portal with fully accessible, component-based UI. Built with SDC, Twig, and Layout Builder enabling editorial teams to manage complex content structures independently.",
        stack: ["Drupal 9", "SDC", "Twig", "Layout Builder", "SASS", "WCAG"],
      },
      {
        num: "02",
        category: "Medical Tech · Drupal 9",
        title: "Nerivio",
        description: "Migrated legacy CSS theming to utility-first Tailwind CSS architecture — significantly reducing stylesheet size, improving load times and long-term maintainability.",
        stack: ["Drupal 9", "Tailwind CSS", "Layout Builder", "SDC"],
      },
    ],
    grid: [
      {
        category: "Higher Ed · Drupal",
        title: "Zayed University",
        description: "Custom module for JSON data sharing with external frontend systems plus full Drupal theming.",
        stack: ["Drupal", "Custom Module", "JSON API"],
      },
      {
        category: "Finance · Drupal 8",
        title: "BMO Global Asset Management",
        description: "Financial services web presence with compliance-driven UI and Layout Builder page management.",
        stack: ["Drupal 8", "Layout Builder"],
      },
      {
        category: "Non-Profit · Drupal 9",
        title: "Heritage Foundation",
        description: "Content-rich editorial platform with Paragraphs and Views for flexible content management.",
        stack: ["Drupal 9", "Paragraphs", "Views"],
      },
      {
        category: "Real Estate · Drupal 8",
        title: "Great Southern Homes",
        description: "High-performance property search with Elastic Search integration across large content libraries.",
        stack: ["Drupal 8", "Elastic Search", "Custom Theme"],
      },
      {
        category: "Tech · Drupal 8",
        title: "EDB (EnterpriseDB)",
        description: "Complex data collection and display workflows using Drupal Webform and custom Views.",
        stack: ["Drupal 8", "Webform", "Views"],
      },
      {
        category: "F&B · Drupal 8",
        title: "Barbeque Nation",
        description: "Restaurant chain digital presence with custom theming and structured content management setup.",
        stack: ["Drupal 8", "Custom Theming"],
      },
      {
        category: "IoT · Drupal 8",
        title: "Ubicquia",
        description: "Full custom redesign maintaining brand consistency with pixel-perfect theming.",
        stack: ["Drupal 8", "Full Redesign"],
      },
      {
        category: "Industrial · Drupal",
        title: "First Industrial",
        description: "Custom theming from scratch for internal enterprise site with performance-focused architecture.",
        stack: ["Drupal", "Custom Theme"],
      },
      {
        category: "Multiple · Drupal 8",
        title: "SEMI · Hologic · Zetes",
        description: "Three enterprise clients built with SDC, Paragraphs, Views, and Layout Builder on Drupal 8.",
        stack: ["Drupal 8", "SDC", "Layout Builder"],
      },
    ],
  },
  publications: {
    label: "Publications",
    heading: "Technical Writing",
    items: [
      {
        platform: "Specbee Blog · Technical Article",
        title: "Writing Smarter Drupal Code Starts with package.json",
        description: "A deep-dive into leveraging package.json for smarter, maintainable Drupal frontend workflows — covering npm scripts, task automation, and modern build tooling for Drupal themes.",
        link: "https://www.specbee.com/blogs/writing-smarter-drupal-code-starts-with-package-json",
      },
      {
        platform: "Specbee Blog · Technical Article",
        title: "Starterkit Theme in Drupal 10",
        description: "A comprehensive guide to Drupal 10's Starterkit theming system — covering scaffolding, customization, and modern development workflows for creating custom themes from scratch.",
        link: "https://www.specbee.com/blogs/starterkit-theme-in-drupal-10",
      },
      {
        platform: "Specbee Blog · Author Profile",
        title: "All Articles by Ashutosh Ahirwal",
        description: "Browse the full collection of technical articles on Drupal theming, SDC architecture, and frontend development published on the Specbee blog — one of the leading Drupal agency blogs globally.",
        link: "https://www.specbee.com/blogs/aashutosh-ahirwal",
      },
      {
        platform: "Drupal.org · Module Maintainer",
        title: "Contributed Modules & Themes",
        description: "Maintainer of contributed modules and themes on Drupal.org. Active in issue queues, patch submissions, and community contribution sprints across multiple Drupal versions.",
        link: "https://www.drupal.org/u/ashutosh-ahirwal",
      },
    ],
  },
  community: {
    label: "Open Source",
    heading: "Community Contributions",
    credits: "105+",
    creditsLabel: "Drupal.org Credits",
    creditsSub: "Across modules, themes,\ncore patches & community sprints",
    items: [
      {
        title: "Module / Theme Maintainer",
        sub: "Contributed projects published on drupal.org/u/ashutosh-ahirwal",
        color: "gold",
      },
      {
        title: "Drupal Core Patches",
        sub: "Patches submitted during community contribution sprints",
        color: "teal",
      },
      {
        title: "Issue Queue Participation",
        sub: "Active in Views, Layout Builder, SDC & core issue queues",
        color: "purple",
      },
      {
        title: "Technical Blog Author",
        sub: "3+ articles on Specbee Blog reaching the global Drupal community",
        color: "gold",
      },
      {
        title: "Community Sprint Participant",
        sub: "Regular contributor during Drupal global contribution events",
        color: "teal",
      },
      {
        title: "Junior Developer Mentor",
        sub: "Mentored 2–3 junior devs at Specbee via code reviews & pair programming",
        color: "purple",
      },
    ],
  },
  tools: {
    label: "Toolbox",
    heading: "Tools & Workflow",
    pills: [
      { name: "Drupal 8/9/10/11", color: "gold" },
      { name: "Storybook", color: "teal" },
      { name: "Pattern Lab", color: "teal" },
      { name: "SDC", color: "gold" },
      { name: "Tailwind CSS", color: "purple" },
      { name: "Twig", color: "gold" },
      { name: "SASS / SCSS / LESS", color: "teal" },
      { name: "JavaScript ES6+", color: "purple" },
      { name: "PHP", color: "gold" },
      { name: "Drush", color: "teal" },
      { name: "Composer", color: "gold" },
      { name: "Git / GitHub / Bitbucket", color: "purple" },
      { name: "Pantheon", color: "teal" },
      { name: "Jira / Monday / ClickUp", color: "gold" },
      { name: "VS Code", color: "purple" },
      { name: "Ubuntu / macOS", color: "teal" },
      { name: "Elastic Search", color: "gold" },
      { name: "WCAG Accessibility", color: "purple" },
      { name: "Docker / DDEV", color: "teal" },
      { name: "SEO Best Practices", color: "gold" },
    ],
  },
  education: {
    label: "Education",
    heading: "Academic Background",
    items: [
      {
        degree: "B.E. — Computer Science & Engineering",
        field: "Bachelor of Engineering",
        school: "Chameli Devi Group of Institutions",
        year: "2019 — 2022",
        location: "Indore, Madhya Pradesh",
      },
      {
        degree: "Diploma — Computer Science & Engineering",
        field: "Polytechnic Diploma",
        school: "Shri Vaishnav Polytechnic College",
        year: "2016 — 2019",
        location: "Indore, Madhya Pradesh",
      },
    ],
  },
  contact: {
    label: "Let's Connect",
    heading: "Got a project?",
    ghost: "Let's build it.",
    email: "ashutosh15798@gmail.com",
    phone: "+91 93403 01969 · Jaipur, Rajasthan",
    cta: "Start a Conversation →",
    socialLinks: [
      { name: "LinkedIn", href: "https://www.linkedin.com/in/ashutosh-ahirwal-546859184" },
      { name: "Drupal.org", href: "https://www.drupal.org/u/ashutosh-ahirwal" },
      { name: "Specbee Blog", href: "https://www.specbee.com/blogs/aashutosh-ahirwal" },
      { name: "Portfolio", href: "https://ashutoshahirwal.netlify.app" },
    ],
  },
  footer: {
    copyright: "© 2026 Ashutosh Ahirwal",
    text: "Senior Drupal Frontend Developer · Dotsquares India · Jaipur",
    languages: "Hindi & English · Indian",
  },
};
